### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by KanwarpartapSinghBimrah** [lvamsavarthan/Media-Toolbox#1]
I am checking this source code and here I got an error. TheApplication.java contain an error that DaggerAppComponent is missing in the source code.

`com.amsavarthan.apps.media_toolbox.WhatsApp.injection.component.**DaggerAppComponent**`

**Comment by lvamsavarthan** [comment]
I have updated the repo, If still this exists you may need to update your Android Studio and sync again
